name: Apertium Monolingual CI/CD

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
          sudo apt-get install -qfy apertium-dev apertium-lex-tools cg3-dev gawk pkg-config
      - name: Build and test
        run: |
          ./autogen.sh
          make -j2
          make test